#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.0b1 on Tue Nov 13 22:34:38 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((903, 668))
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.frame_menubar.Append(wxglade_tmp_menu, "Quit")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Beta"), wx.HORIZONTAL)
        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Alpha"), wx.HORIZONTAL)
        sizer_2.Add((20, 20), 0, 0, 0)
        bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/Users/brendan/Sandbox/wxglade-panel-feature-request/cat.png", wx.BITMAP_TYPE_ANY))
        bitmap_1.SetBackgroundColour(wx.Colour(255, 255, 0))
        sizer_2.Add(bitmap_1, 1, 0, 0)
        bitmap_2 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/Users/brendan/Sandbox/wxglade-panel-feature-request/shield.png", wx.BITMAP_TYPE_ANY))
        bitmap_2.SetBackgroundColour(wx.Colour(255, 255, 0))
        sizer_2.Add(bitmap_2, 1, 0, 0)
        bitmap_3 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/Users/brendan/Sandbox/wxglade-panel-feature-request/bulb.png", wx.BITMAP_TYPE_ANY))
        bitmap_3.SetBackgroundColour(wx.Colour(255, 255, 0))
        sizer_2.Add(bitmap_3, 1, 0, 0)
        sizer_2.Add((20, 20), 1, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.ALL | wx.EXPAND, 10)
        sizer_3.Add((20, 20), 1, 0, 0)
        bitmap_4 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/Users/brendan/Sandbox/wxglade-panel-feature-request/heart.png", wx.BITMAP_TYPE_ANY))
        bitmap_4.SetBackgroundColour(wx.Colour(143, 188, 143))
        sizer_3.Add(bitmap_4, 1, 0, 0)
        sizer_3.Add((20, 20), 1, 0, 0)
        bitmap_5 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/Users/brendan/Sandbox/wxglade-panel-feature-request/add.png", wx.BITMAP_TYPE_ANY))
        bitmap_5.SetBackgroundColour(wx.Colour(143, 188, 143))
        sizer_3.Add(bitmap_5, 1, 0, 0)
        sizer_3.Add((20, 20), 1, 0, 0)
        bitmap_6 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/Users/brendan/Sandbox/wxglade-panel-feature-request/error.png", wx.BITMAP_TYPE_ANY))
        bitmap_6.SetBackgroundColour(wx.Colour(143, 188, 143))
        sizer_3.Add(bitmap_6, 1, 0, 0)
        sizer_3.Add((20, 20), 1, 0, 0)
        sizer_1.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 10)
        sizer_4.Add((20, 20), 1, 0, 0)
        bitmap_7 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/Users/brendan/Sandbox/wxglade-panel-feature-request/check.png", wx.BITMAP_TYPE_ANY))
        bitmap_7.SetBackgroundColour(wx.Colour(219, 112, 219))
        sizer_4.Add(bitmap_7, 1, 0, 0)
        sizer_4.Add((20, 20), 1, 0, 0)
        bitmap_8 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/Users/brendan/Sandbox/wxglade-panel-feature-request/star.png", wx.BITMAP_TYPE_ANY))
        bitmap_8.SetBackgroundColour(wx.Colour(219, 112, 219))
        sizer_4.Add(bitmap_8, 1, 0, 0)
        sizer_4.Add((20, 20), 1, 0, 0)
        bitmap_9 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/Users/brendan/Sandbox/wxglade-panel-feature-request/map.png", wx.BITMAP_TYPE_ANY))
        bitmap_9.SetBackgroundColour(wx.Colour(219, 112, 219))
        sizer_4.Add(bitmap_9, 1, 0, 0)
        sizer_4.Add((20, 20), 0, 0, 0)
        sizer_1.Add(sizer_4, 1, wx.ALL | wx.EXPAND, 10)
        self.SetSizer(sizer_1)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
